version: "2"
services:

  base-application:
    build: .
    environment:
      - APPLICATION_PORT=9000
    expose:
      - 9000
    ports:
      - 9000:9000

  development-application:
    extends: base-application

  test-application:
    extends: development-application
  test-http-interface:
    image: 21stio/dredd
    volumes:
      - ./swagger.yaml:/swagger.yaml
    links:
      - test-application:application
    command: dredd /swagger.yaml application:9000 --server-wait 3